name: Test CI|CD

on:
  push:
    branches: [master]

    schedule:
   - cron: "*/5 * * * *"
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
        - name: Install Dependencies
          run: composer install
           - name: Generate key
           run: php artisan key:generate           




